### ISSUE TITLE
argument and yaml parsing type errors

### ISSUE THREAD

**Issue by arthurlm44** [helm/helm#3005]
Since upgrading to helm 2.6.1, from 2.5.1 I've been encountering this issue:

```
Error: render error in "instastage/templates/service.yaml": template: instastage/templates/service.yaml:1:5: executing "instastage/templates/service.yaml" at <eq .Values.replicaCo...>: error calling eq: incompatible types for comparison
```

The helm command is:
```
helm install --debug --dry-run --set replicaCount=1,anotherVar=someothervalue ~/workspace/charts/mychart
```

and the chart starts with:
```
{{if eq .Values.replicaCount 1.0}}
```

This worked fine in 2.5.1 but is broken in 2.6.1

I've tried from file via `-f` flag but get the same type error.

Strings are parsed fine, but integers (which used to be automatically converted to floats, which in itself was a bug) are no longer coming in as either integers or floats and vice-versa.

I've attempted to pass ints, and floats and have attempted int and float comparison to no avail.

**Comment by bacongobbler** [comment]
To give others some background on why the chart uses a float-point value instead of an int, it's due to some issues with the --set parser with ints being converted to scientific notation in some cases as seen in #1707.

We've attempted a multitude of --set attempts over slack with @arthurlm44 yesterday afternoon:

```
--set replicaCount=1
--set replicaCount=1.0
--set replicaCount="1.0"
--set replicaCount=1\.0
--set replicaCount="1\.0"
--set replicaCount=\"1.0\"
```

None of the above worked. Regardless of the argument whether replica count should be an integer or not, we should find a way to parse floating point values and document it.

The ugly workaround is to use a literal string for now.

```
{{ if eq .Values.replicaCount "one" -}}
replicas: 1
{{- else -}}
replicas: 0
{{- end }}
```

**Comment by hobti01** [comment]
I have a related issue without using set, Helm v2.6.2.  Thanks for the hints here to get a workaround.

Does not work:
values.yaml
```
replicas: 1
```
templates/test.yaml
```
{{- if gt .Values.replicas 1 }}
Greater than one
{{- end }}
```
Output:
```
$ helm install --debug --dry-run my-chart
...
Error: render error in "my-chart/templates/test.yaml": template: my-chart/templates/test.yaml:1:7: executing "my-chart/templates/test.yaml" at <gt .Values.replicas ...>: error calling gt: incompatible types for comparison
```

Does work:
values.yaml
```
replicas: 2
```
templates/test.yaml
```
{{- if gt .Values.replicas 1.0 }}
Greater than one
{{- end }}
```

```
$ helm install --debug --dry-run my-chart
...
---
# Source: my-chart/templates/test.yaml

Greater than one
```

**Comment by ljnelson** [comment]
This just occurred to me out of the blue and I thought I'd at least capture it here.  Would something like this work:

    --set replicaCount="!!int '1.0'"

…?  `!!int` applied to a YAML scalar is supposed to coerce it.

**Comment by bacongobbler** [comment]
Assuming https://github.com/ghodss/yaml supports it, yes.

**Comment by so0k** [comment]
Still facing this issue

**Comment by cgebe** [comment]
same as @hobti01 

issue still occurs - `v2.9.0`:
```
Error: render error in "server/templates/deployment.yaml": template: server/templates/deployment.yaml:36:7: executing "server/templates/deployment.yaml" at <gt .Values.replicaCo...>: error calling gt: incompatible types for comparison
```

```
{{- if gt .Values.replicaCount 1 }}
                 ...
{{- end}}
```

**Comment by ljnelson** [comment]
Out of curiosity, could you try `--set replicaCount="!!int '1'"`?

**Comment by artushin** [comment]
To clarify the workaround from @so0k, if doing something like `{{- if eq .Values.replicas 1.0 }}`, the second arg should be the float so that you don't have to cast `.Values.replicas`.

**Comment by jb-sean** [comment]
I got around this by piping the variables to [`int64`](http://masterminds.github.io/sprig/conversion.html).

For instance, to check whether my hpa's max number of replicas was less than or equal to the number of credentials I had, I did this:
```golang
{{ le (.Values.hpa.maxReplicas | int64) (len .Values.app.credentials | int64) }}
```

This workaround isn't pretty, but it works for me.

**Comment by bacongobbler** [comment]
given that there hasn't been any activity in the last 3 years to address this since it was first opened, I'm going to close this as community members have found workarounds to the issue, and that seems to solve the problem.
